### ISSUE TITLE
Sleep wake issue

### ISSUE THREAD

**Issue by aidanchandra** [aidanchandra/x1c7-hackintosh#1]
Just saw sleep wake failure in EFI error.

State info:
- PC plugged in for a long time
- No power button wake, no keyboard wake
- USB efi boot was unplugged prior to going to sleep
- Hibernatemode was 3

**Comment by aidanchandra** [comment]
I set hibernate mode to 0. Coulda swore it was working with 3 before. Will keep track.

**Comment by seven-of-eleven** [comment]
I've had it once on mine but I haven't done any trouble shooting on it. Let me know if setting hibernate to 0 is the fix.

**Comment by aidanchandra** [comment]
Hibernatemode 0 is working fine.

Proper deep hibernation is on the todo list.

**Comment by aidanchandra** [comment]
Closing as the issue disappeared with hibernatemode 0. Will revisit with different and better modes as part of nvmefix.
