### ISSUE TITLE
Doesn't boot with Intel iGPU spoof enabled

### ISSUE THREAD

**Issue by drizzt** [aidanchandra/x1c7-hackintosh#11]
Hi,

I'm trying to launch Catalina installer on 20QE-SP40U (that is almost the same as 20QE-S01L00), but with default config it doesn't boot (it stucks after "IOConsoleUsers: gIOScreenLock..."). I already followed the [guide](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/userspace-issues.html#stuck-on-or-near-ioconsoleusers-gioscreenlock-giolockstate-3) without any success.

If I disable the Intel iGPU spoof it boots, with in VESA mode

Any clue?

**Comment by suhrmann** [comment]
I cant find hardware specs of your model. Could you please provide the CPU model?

**Comment by drizzt** [comment]
Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz with UHD Graphics 620 (Whiskey Lake)

**Comment by aidanchandra** [comment]
I was getting that exact same issue as you a month or so ago but I could have sworn I fixed it. In fact, I know I did. However, I remember @suhrmann removed just a few things from my framebuffer patch and the EFI still worked on my machine so I thought nothing of it.

Let me dig up that original EFI with a very large framebuffer entry and let's see if that works for you. I have the exact same CPU as you and saw the same issue and this solved it.

Only mystery is why this is happening even when this current EFI W/O the huge framebuffer is working for me but not for you. Maybe some static register in the CPU or some garbo that I can't comprehend lol.

Give me a sec.

**Comment by aidanchandra** [comment]
There's the config.plist that had all the framebuffer garbage that allowed me to get past giolockstate3 error. Please let me know if you have any issues copying it over.

[config.plist.zip](https://github.com/aidanchandra/x1c7-hackintosh/files/6143707/config.plist.zip)

**Comment by drizzt** [comment]
I merged config.plist (by only replacing the `PciRoot(0x0)/Pci(0x2,0x0)` section) on top of last main and 1.0.0, but it still doesn't work

**Comment by drizzt** [comment]
Ok, I solved the problem by just adding `-igfxmlr` on top of 1.0.0

**Comment by aidanchandra** [comment]
Ok good to hear. Thanks for reporting back. I'll mark and close this.
