### ISSUE TITLE
Audio Layout for 4 speakers

### ISSUE THREAD

**Issue by huyhoang8398** [aidanchandra/x1c7-hackintosh#12]
I tried 11, 21, 31, 52 and 71 none of these layout work for 4 speaker

If you report a problem, provide at least these information and if so the device: 
```
Lenovo Model
Thinkpad x1 carbon gen 7 20R1 R2

CPU
i5 10210U

```

**Comment by huyhoang8398** [comment]
![Screenshot 2021-03-24 at 22 12 25](https://user-images.githubusercontent.com/25379882/112383920-0cd01280-8cee-11eb-9fd6-a4db9a2130b4.png)
there are 2 internal speaker, the first one is 2 top speaker, and the 2nd one is two bottom speaker

**Comment by suhrmann** [comment]
What are your results when running this command in terminal?
```bash
kextstat | grep -E "AppleHDA|AppleALC|Lilu"
```

https://dortania.github.io/OpenCore-Post-Install/universal/audio.html#fixing-audio-with-applealc

**Comment by huyhoang8398** [comment]
@suhrmann 
![image](https://user-images.githubusercontent.com/25379882/112396282-21b5a180-8d00-11eb-9e9c-c02a240f5a45.png)

**Comment by aidanchandra** [comment]
Go to Midi Audio Settings and create an aggregate device, although it may not let you adjust volume of the device once you've done so.

**Comment by huyhoang8398** [comment]
@aidanchandra  what is your AppleAlc version, thus I see the same issues with Alc285 from this repo https://github.com/jpransxdev/HP-Spectre-X360-13-Early-2019-Hackintosh

**Comment by huyhoang8398** [comment]
> Go to Midi Audio Settings and create an aggregate device, although it may not let you adjust volume of the device once you've done so.

Im currently using it, but it a little anoying

**Comment by aidanchandra** [comment]
Sorry I misunderstand what your problem is then if you've already got the aggregate device working? _Please be more clear._
Also, my appleALC version is exactly what is on this repo.

**Comment by huyhoang8398** [comment]
> Sorry I misunderstand what your problem is then if you've already got the aggregate device working? _Please be more clear._
> Also, my appleALC version is exactly what is on this repo.

sorry for asking unclear question, I mean do we have a better solution for combining 4 speaker?

**Comment by aidanchandra** [comment]
Simply put, there is no better solution. Realtek alone makes approx 800 different codecs, many of which are active in production. Apple only uses a handful of them by default. Opencore and appleALC are therefore made to work across nearly thousands of different codecs. AppleALC is **amazing** at doing everything ok and bad at doing specific CODECs perfectly. Sadly, we are one of the unlucky codecs.

There's a process to add full support for a new codec to AppleALC. Please go to their repo and investigate. If you would like this repo's help, I can say for a fact that I'm glad to help out, but your efforts are not meant to be directed here, but rather, on their kext.

Best

Aidan
