### ISSUE TITLE
HDMI  output doesn't work

### ISSUE THREAD

**Issue by shangjun2x** [aidanchandra/x1c7-hackintosh#13]
Lenovo Model: Yoga X1 20QG-S1630J 

CPU: Intel i7-8665U 
Graphic: UHD 620
Device
HDMI output doesn't work with external DELL display 2560x1440

I used your latest version.

Thanks

**Comment by suhrmann** [comment]
Please use the template:
Describe your issue here. Lorem ipsum...

If you report a problem, provide at least these information and if so the device: 
```
Lenovo Model
< Your Lenovo Model, e.g.: 20QE-S01L00 >

CPU
< Your exact(!) CPU model, e.g.: Intel i7-8565U >

Device
< If a device is causing problems, e.g.: Broadcom 4360 802.11ac >

EFI
<A link would be great! But at the VERY least please tell us if you are using our exact efi and if not what modifications you applied>
```

**Comment by aidanchandra** [comment]
HDMI output wasn't working for me at work the other day. I'll investigate later. It works through thunderbolt or USB-C, just not the HDMI connector itself.
Adding HDMI support is definitely doable and I'm glad to help out, but in all honesty, this is a nonpriority for me. However, if you research and share your research, or even better, a branch of your HDMI fix, I'll support as much as I can and add it to this repo.

**Comment by shangjun2x** [comment]
> HDMI output wasn't working for me at work the other day. I'll investigate later. It works through thunderbolt or USB-C, just not the HDMI connector itself.
> Adding HDMI support is definitely doable and I'm glad to help out, but in all honesty, this is a nonpriority for me. However, if you research and share your research, or even better, a branch of your HDMI fix, I'll support as much as I can and add it to this repo.

Thank you. Type-c works for me.

**Comment by aidanchandra** [comment]
Closing this until further efforts to fix or development
