### ISSUE TITLE
iMessgae and facetime don't work without SMBIOS, Web camera and Bluetooth don't work with SMBIOS

### ISSUE THREAD

**Issue by shangjun2x** [aidanchandra/x1c7-hackintosh#14]
Lenovo Model: Yoga X1 20QG-S1630J

CPU: Intel i7-8665U
Graphic: UHD 620

**Comment by suhrmann** [comment]
iMessgae and facetime not working without SMBIOS is obvious.

Bluetooth depends on OpenIntelWireless, Web Camera depends on ACPI patches. Would you mind posting your Bluetooth device?

**Comment by shangjun2x** [comment]
Thanks @suhrmann. I am not a tech man.After applying SMBIOS MacBook pro 15.4 or MacBook Pro 15.1, both Bluetooth and web camera disppear on hardware list.
 
<img width="1920" alt="Screen Shot 2021-03-28 at 8 37 23 PM" src="https://user-images.githubusercontent.com/23515854/112752490-eb309d00-9005-11eb-9e3e-78ceda4b8223.png">
<img width="408" alt="Screen Shot 2021-03-28 at 8 43 28 PM" src="https://user-images.githubusercontent.com/23515854/112752594-5e3a1380-9006-11eb-8457-65349ca12d85.png">

**Comment by suhrmann** [comment]
This is very weird behaviour. For Bluetooth I recommend following [Troubleshooting of IntelBluetoothFirmware [OpenIntelWireless]](https://openintelwireless.github.io/IntelBluetoothFirmware/Troubleshooting.html) ... but it is recognized correctly as Intel Bluetooth device - so in general it works.

We use SMBIOS of MacBookPro14,4 - just like you noted.

**Comment by shangjun2x** [comment]
thanks for the suggestion.
