### ISSUE TITLE
[Kext] ECEnabler  - Instant battery status - no more ACPI patches?

### ISSUE THREAD

**Issue by huyhoang8398** [aidanchandra/x1c7-hackintosh#17]
ECEnabler is a Lilu plugin which allows macOS to read any size of EC field, meaning that no more ACPI patches are needed to split EC fields up within ACPI.

I have been using it for a while and it works great. Thinkpad x1 7th 20R1

**Comment by suhrmann** [comment]
[ECEnabler](https://github.com/1Revenger1/ECEnabler) works great on my other Hack. Though, I dont see a reason to use it over our custom generated and working ACPI patches.

**Comment by aidanchandra** [comment]
I'll echo what @suhrmann said. It's not even if it ain't broke don't fix it - it's indistinguishable from the other option. However, we appreciate the suggestion. Feel free to reopen this if there's evidence to swap and I'll look into it.
