### ISSUE TITLE
Battery Charge Indicator Issue

### ISSUE THREAD

**Issue by aidanchandra** [aidanchandra/x1c7-hackintosh#2]
See "battery not charging" when plugged in.
Unplug charger
Battery charge jumps up.

**Comment by seven-of-eleven** [comment]
I don't have this issue at all. I can plug in and unplug without issue. Maybe check your BIOS settings. I thought there was something for USB charging in there.  I can take a look at mine and let you know what they are set at.

**Comment by seven-of-eleven** [comment]
So I have the following settings:
Config
- `Always on USB` **Enabled**
- `Charge in Battery Mode` **Disabled**

Power
- `CPU Power Management` **Enabled**
- `Power On with AC Attached` **Disabled**
- `Sleep State` **Linux**

Not sure if any of that helps.

**Comment by aidanchandra** [comment]
I'll take a look. I haven't seen the issue since then. It may be intermittent.

**Comment by aidanchandra** [comment]
I'm going to close this issue. I've seen the issue a few times but it's honestly very low priority. I'm going to assign wontfix for the time being.
Thx @seven-of-eleven for the help.
