### ISSUE TITLE
Working With X1C7 10710u model

### ISSUE THREAD

**Issue by muhchaudhary** [aidanchandra/x1c7-hackintosh#4]
After applying:

Cpuid1Data: EC060800 00000000 00000000 00000000
Cpuid1Mask: FFFFFFFF 00000000 00000000 00000000

Everything is working perfectly aside from the internal microphone and some skipping on the trackpad

**Comment by aidanchandra** [comment]
So so glad to hear! That's why @suhrmann and I spent so much time on it :)

We are actively investigating the internal microphone. Can you do me a favor and test it out in windows if you have that partition still?

Also, let me know if you have any other questions boss. I'll add your info to our README. Great to hear it's working with 10th gen.

**Comment by muhchaudhary** [comment]
unfortunately, my windows ssd is a sk Hynix model which causes kernel panics so I switched it out for a different SSD which currently only has macOS on it

**Comment by aidanchandra** [comment]
What's ur exact model number/family name (sticker underneath)?

I wanna add ur model name to our guide with credit of coruse

**Comment by huyhoang8398** [comment]
My trackpad is bad with the newest voodoo kext. Anyone has similar issue?

**Comment by suhrmann** [comment]
@huyhoang8398 I dont think this belongs to this issue. Please create a new issue and provide some system information (at least Lenovo model and CPU)

**Comment by aidanchandra** [comment]
@huyhoang8398 Open an issue and I'm glad to help you out!

**Comment by huyhoang8398** [comment]
> @huyhoang8398 Open an issue and I'm glad to help you out!

thanks, I created #5 issue

**Comment by aidanchandra** [comment]
@muhchaudhary 
What's ur exact model number/family name (sticker underneath)?

I wanna add ur model name to our guide with credit of course

**Comment by muhchaudhary** [comment]
sorry for the late reply, 
my model number is 20R1/20R2
the entire product number(written on the sticker) is: 20R1-S05B00

**Comment by aidanchandra** [comment]
Thank you @muhchaudhary !!! I'll add.

would you terribly mind seeing #5 and see if you are seeing similar issues with your trackpad as the poster?

**Comment by suhrmann** [comment]
I created a Wiki page from this issue: https://github.com/aidanchandra/x1c7-hackintosh/wiki/X1C7-Intel-i7-10710U

**Comment by aidanchandra** [comment]
I've added this to README as well. Closing. Thank you again everyone.

**Comment by huyhoang8398** [comment]
Where should i put this if using this EFI in this repo?
