### ISSUE TITLE
Trackpad randomly jumps cursor

### ISSUE THREAD

**Issue by huyhoang8398** [aidanchandra/x1c7-hackintosh#5]
**Bug**
Trackpad is very slow, and un-responsive, difficult for tap to touch, while scrolling sometime the cursors is jumped

**Configuration**

- Opencore
- Thinkpad x1 carbon 7th gen with IceLake CPU
- Extension: 
  - VoodooI2C
  - VoodooInput
  - VoodooPS2Controller
  - VoodooRMI

**Comment by aidanchandra** [comment]
Awesome. Before I can start helping I am going to need the following things.
1. Your exact model number
2. Your EFI
3. Answers to the following quesitons
3a. Does the jumping go away when you simply press down firmer on the trackpad
3b. Have you disabled force touch in VooodooRMI (or I2C, forget which kext it's in)
3c. Is your trackpad detected as a builtin one within System Preferences 
Once I've got those I can start helping diagnosing.

**Comment by huyhoang8398** [comment]
1. X1 Carbon 7th Gen - (Type 20R1, 20R2) Laptop (ThinkPad) - Type 20R1 ( Mine is 20R1)
2. [EFI repo](https://github.com/huyhoang8398/x1c7-hackintosh-20R1)
3a. Yes but it means that I have to firmly touch the trackpad to move cursor, point or scroll
3b. No I have not disabled forcetouch
3c. Yes

**Comment by aidanchandra** [comment]
Great. I'll take a look at your EFI now. It's probably something forcetouch related.

**Comment by aidanchandra** [comment]
Replace your VoodooRMI.kext with ours and see if it helps.
In `Kexts/VoodooRMI.kext (Show package contents)/Info.plist`
We've disabled ForceTouchEmulation and I remember tuning some of the FingerMajorMinor and ThumbDetection things to better fit the smaller trackpad.

**Comment by aidanchandra** [comment]
@huyhoang8398  any success?

**Comment by huyhoang8398** [comment]
> @huyhoang8398 any success?

I have no luck

**Comment by aidanchandra** [comment]
Were there no improvements?
I'm curious if your trackpad is over a different bus than I2C - are you familiar trying to find out what type of bus interface you hvae?

**Comment by muhchaudhary** [comment]
I have the same laptop as @huyhoang8398 and I don't seem to be having the same issues with the trackpad. I have experienced other issues though:

- Fast moments are not registered (swiping quickly using the trackpad leads to the cursor not moving)
- tapping and double tapping is unreliable (buttons work fine, touch tapping is the issue)

other than those two issues, everything on my trackpad works fine including gestures and general movement

**Comment by aidanchandra** [comment]
Thanks @muhchaudhary. 
There are two things here.
1. @huyhoang8398, I believe you are using a different EFI while @muhchaudhary is using our verbatim provided one with his small modification. @huyhoang8398 Please use our identical EFI with @muhchaudhary 's modifications (see #4) and see if that improves your situation.
2. In troubleshooting myself some time ago I learned that the behavior of the trackpad under VooDoo is simply imperfect even at its best. Nothing is exactly going to compare to the real deal from apple. I also realized that as I started using my own X1C7 I learned the peculiar things about the trackpad and my general discomfort using it literally disappeared as I learned to tap and drag a bit more forcefully. What's so hard about debugging is that I can't sit right next to you and do a side by side comparison to the 'working known good' and your X1C7s, but take that into mind when considering whether or not there's an actual bug. Absolutely not saying that this issue doesn't exist, but this is a difficult to quantify feeling-based issue.

**Comment by sreehax** [comment]
I think I have the exact same issue on my 20QD0000US. In fact, I've noticed the exact same issue on OpenBSD (though much less frequently). In both OpenBSD and macOS when I push down the trackpad harder it will move but it's still pretty useless since that's a click

**Comment by sreehax** [comment]
It's much worse on macOS though so I wouldn't say it's the exact same issue.

**Comment by sreehax** [comment]
Update: Trackpad is basically perfect after removing VoodooRMI. I think I found it unnecessary on my old EFI attempt too. I suggest anyone facing issues try the same

**Comment by sreehax** [comment]
There is an issue with normal push clicks on the touchpad being registered as force clicks. Just disable force clicking for a fix (other settings I changed were enabling tap to click and changing natural scrolling)

**Comment by aidanchandra** [comment]
@sreehax  - excellent news! I will add your solution in our README. Thank you so much for fixing this.

@muhchaudhary @huyhoang8398 I am going to close this issue but please feel free to reopen this issue if @sreehax 's fix does not work.

**Comment by aidanchandra** [comment]
Reponeing this. I was away from my X1C7 for a short while and coming back made me realize there was skipping than I had previously though was happening.

Will report back with removing VoodooRMI

**Comment by aidanchandra** [comment]
Yup. Disabling VoodooRMI _massively_ improved trackpad responsiveness and overall feel. For the sake of documentation, I'm going to write my before/after notes below and close the issue. May comment on voodooRMI repo to see what's going on.

Before:
1. Scrolling with decreasing fingertip surface area and would cause scrolling to completely cut out and need a re-tap
2. Tracking with a decreasing fingerprint surface area would cause tracking to cut out and need a retap

After:
1. None of the above behaviors are detected. Smallest finger surface areas are now detected.

@sreehax @huyhoang8398 Thank you both for being on top of this issue and especially @sreehax  for finding the solution. I will disable voodooRMI in the config plist and remove it from the EFI.

**Comment by huyhoang8398** [comment]
Disabling voodooRMI and using PS2 and I2C works great on my x1c7 20R
