### ISSUE TITLE
Big Sur: prohibitory symbol on bootup [20QD0000US]

### ISSUE THREAD

**Issue by sreehax** [aidanchandra/x1c7-hackintosh#7]
I created a Big Sur 11.2.3 USB using an M1 mac and copied over the files from the release, however on bootup the progress bar advances for a bit but then I get hit with a prohibitory symbol and support.apple.com/mac/startup. Is this expected?

**Comment by suhrmann** [comment]
@aidanchandra did a Big Sur attempt as well without success.

**Comment by aidanchandra** [comment]
I actually had success. Only intel wifi/Bluetooth is currently unsupported in Big Sur. I'm away from my desk for a short while, I'll come back later.

**Comment by sreehax** [comment]
Interesting. I have had mixed success with using Big Sur on an EFI based on @suhrmann's old repo in december 2020 and I even made an opencore efi myself once or twice with similar results. In my experience my laptop has booted with Big Sur and installed properly, though there was some major glitchiness (the builtin display seems to have weird colors, maybe in 6 bit mode, and sometimes it even flashes weirdly, and I could never fix this issue for the life of me). Basically I have gotten Big Sur 11 to at least boot on my machine in the past. Additionally I've used AirportItlwm for working wifi on Big Sur (802.11n since it's a ripped out OpenBSD driver), though I never tried bluetooth. (In my version I never bothered trying to figure out how to patch battery either)

**Comment by aidanchandra** [comment]
Ah yes - it was bluetooth only that didn't work. I now remember.
There are only two key differences that I can see from my attempt with this EFI and your attempt with this EFI.
I upgraded from Catalina to Big Sur directly within MacOS itself.
I created the original Catalina Installer on an intel mac.

Also by prohibitory do you mean the circle with the cross through it? I've definitely never seen that so that is odd.

**Comment by sreehax** [comment]
Interesting. I might try installing Catalina first then upgrading to Big Sur. If I remember properly I actually needed to do that on @suhrmann's EFI but not my own one from scratch. As for this EFI, I can definitely try to create a Catalina USB, though I don't actually have an Intel mac. Also I do mean a circle with a cross through it, which I'm 99% sure means that macOS detected it's not running on apple hardware, so some kind of spoofing failed. I'll try installing Catalina first

**Comment by sreehax** [comment]
Well then it seems that running catalina's createinstallmedia on my m1 macbook causes it to die. I guess the best I can do is catalina online install from linux

**Comment by sreehax** [comment]
Oh yeah forgot to ask but what BIOS Settings should I change?

**Comment by sreehax** [comment]
Ok I've booted Catalina 10.15.7, and in the installer I can see that there's the same trackpad iffyness as before (I also observe this on OpenBSD but not FreeBSD or Linux) and color banding is still an issue, but the system did boot properly!

**Comment by sreehax** [comment]
Additionally I've updated to Big Sur 11.2.3 by copying Install macOS Big Sur.app from my m1 mac to an ssd then copying from the ssd to the Thinkpad (wifi wasn't working on the installed macOS Catalina for whatever reason), and the upgrade to Big Sur worked out fine and wifi worked again.

**Comment by suhrmann** [comment]
> Interesting. I might try installing Catalina first then upgrading to Big Sur. If I remember properly I actually needed to do that on @suhrmann's EFI but not my own one from scratch.

If you mean installing with suhrmann/x1c7-hackintosh: The reason why to use a slim EFI for install is for easier trouble shooting. So if aidanchandra/x1c7-hackintosh works for Catalina, installation should actually™ also work for Big Sur

**Comment by sreehax** [comment]
Yeah that's understandable and in the end it did work out

**Comment by aidanchandra** [comment]
I need to add the BIOS settings to the Readme. I'll add it to my todo list.

Can you confirm that bluetooth does not work on Big Sur?

**Comment by sreehax** [comment]
Actually I did get bluetooth working (paired my MTW2 bluetooth earphones under 11.2.3 and played audio though i think trying to use the mic didn't work and hung stuff), though I downloaded the latest AirportItlwm for big sur. Maybe I should try the latest \*Bluetooth\* stuff too

**Comment by aidanchandra** [comment]
Oh perfect! So you have Bluetooth AND WiFi working... great! I would try to get big sur running on my machine but I have it on my real mac and kind of hate it.

Would you mind sending over a screenshot for our readme? I'll add it (with credit) and link this issue.

**Comment by sreehax** [comment]
I think I might know what the cause of this is. Basically, I noticed another strange issue: USB 3.0 devices don't work (usb ssd and usb 3.1 flash drive) but USB 2.0 devices work fine (my OnePlus 6T connected over USB and an ancient usb drive). Additionally, I noticed these notes about the prohibited symbol on the OpenCore troubleshooting guide: [https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html), scroll to "Waiting for Root Device" or Prohibited Sign error". Basically it could be USB issues causing macOS Big Sur to fail to boot

**Comment by sreehax** [comment]
Oops I started writing that before your recent comment but yeah I suspect a USB issue caused the problems with the big sur recovery image, and still doesn't allow USB 3.0 devices to work properly (for me at least, I'm not sure if anyone else is affected)

**Comment by aidanchandra** [comment]
Ok gotcha. I see you moved this issue to #10. Let's focus there. Sorry for delayed reply!
